<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>

		<TargetFramework>net10.0-windows</TargetFramework>

		<UseWPF>true</UseWPF>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>

		<Nullable>enable</Nullable>

		<ImplicitUsings>enable</ImplicitUsings>

		<LangVersion>latest</LangVersion>

		<EnableDefaultPageItems>true</EnableDefaultPageItems>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MjpegProcessor" Version="1.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Refit" Version="10.1.6" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\logo.png" />
	</ItemGroup>

</Project>